version: 2

jobs:
        build_setup_py:
                docker:
                        - image: python:latest
                steps:
                        - checkout
                        - run:
                                name: Install Enigma with setup
                                command: python -m pip install .
                        - run:
                                name: Run Unit Tests
                                command: nose2
        build_poetry:
                docker:
                        - image: python:latest
                steps:
                        - checkout
                        - run:
                                name: Install Poetry
                                command: python -m pip install poetry
                        - run:
                                name: Install Enigma in Poetry
                                command: poetry install
                        - run:
                                name: Run Unit Tests
                                command: poetry run nose2

workflows:
        version: 2
        build_and_test:
                jobs:
                        - build_setup_py
                        - build_poetry