[tool.poetry]
name = "enigma"
version = "1.1.4"
description = "Enigma Machine Emulator for Python."
authors = ["Kristian Zarebski <krizar312@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
hypothesis = "^5.41.0"
nose2 = "^0.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
