name: python3.7
on: [push]
jobs:
    build:
      name: Ubuntu (Python3.7)
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Python 3.7
          uses: actions/setup-python@v2
          with:
            python-version: 3.7
        - name: Install Poetry and AnyBadge
          run: python -m pip install poetry anybadge
        - name: Install Enigma
          run: poetry install
        - name: Run Unit Tests
          run: poetry run pytest
