name: python3.13
on: [push]
jobs:
    build:
      name: Ubuntu (Python3.13)
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup Python 3.13
          uses: actions/setup-python@v5
          with:
            python-version: 3.13
        - name: Install Poetry
          run: python -m pip install poetry
        - name: Install Enigma
          run: poetry install
        - name: Run Unit Tests
          run: poetry run pytest

