name: python3.10
on: [push]
jobs:
    build:
      name: Ubuntu (Python3.10)
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup Python 3.10
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - name: Install Poetry
          run: python -m pip install poetry
        - name: Install Enigma
          run: poetry install
        - name: Run Unit Tests
          run: poetry run pytest